server:
  port: 8083
spring:
  application:
    name: "reports"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

aws:
  region: "us-east-1"
  secrets:
    jwt-key-pair: "jwt/rsa/keys"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "${AWS_LOAN_REPORT_SQS_QUEUE_URL}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
